package pojo;
// Generated 02.May.2020 03:58:38 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Dolap generated by hbm2java
 */
public class Dolap  implements java.io.Serializable {


     private Integer pri;
     private int alarm;
     private float derece;
     private int id;
     private Date time;

    public Dolap() {
    }

    public Dolap(int alarm, float derece, int id, Date time) {
       this.alarm = alarm;
       this.derece = derece;
       this.id = id;
       this.time = time;
    }
   
    public Integer getPri() {
        return this.pri;
    }
    
    public void setPri(Integer pri) {
        this.pri = pri;
    }
    public int getAlarm() {
        return this.alarm;
    }
    
    public void setAlarm(int alarm) {
        this.alarm = alarm;
    }
    public float getDerece() {
        return this.derece;
    }
    
    public void setDerece(float derece) {
        this.derece = derece;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


